# Generated by Django 2.2 on 2020-11-30 21:13

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Educations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deparment', models.CharField(choices=[('default', 'Choose Option'), ('school', 'School Name'), ('collage', 'Collage Name'), ('tution', 'Tution Name'), ('course', 'Course Name')], default='default', max_length=80)),
                ('logo', models.ImageField(default='default.jpg', upload_to='school/logo')),
                ('bg_image', models.ImageField(default='default.jpg', upload_to='school/bg')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('discription', models.TextField()),
            ],
            options={
                'verbose_name': 'School',
                'verbose_name_plural': 'School Name',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('video_link', models.URLField(blank=True, null=True)),
                ('name', models.CharField(max_length=300)),
                ('discription', ckeditor_uploader.fields.RichTextUploadingField()),
                ('choice_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='corecode.StudentClass')),
                ('choice_school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='corecode.Educations')),
                ('choice_subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='corecode.Subject')),
            ],
            options={
                'verbose_name': 'subjectvideo',
                'verbose_name_plural': 'Subject video',
                'ordering': ['choice_school'],
            },
        ),
    ]
