# Generated by Django 3.1.3 on 2021-06-07 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0002_educations_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='educations',
            old_name='deparment',
            new_name='department',
        ),
    ]
